<?php
/** @var \Lumav\DaireStudyUnit4list\Block\VendorDetails $block */
$vendorId = $block->getCurrentVendorId();
$vendorData = $block->getVendorWProducts($vendorId);
?>
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>
<div>
    <?php
    if ($vendorData && count($vendorData) > 0) {
        ?>
        <div>
            <span>vendor id <?= __($vendorData[0]['vendor_id']) ?></span>
            <span>vendor name <?= __($vendorData[0]['name']) ?></span>
        </div>
        <div>
            <table>
                <tr>
                    <td>product id</td>
                </tr>
                <?php
                foreach ($vendorData as $item) {
                    ?>
                    <tr>
                        <td><?= __($item['product_id']) ?></td>
                    </tr>
                    <?php
                }
                ?>
            </table>
        </div>
        <?php
    }
    ?>
</div>
