
<?php
/**
 * Product list toolbar
 *
 * @var $block \Lumav\DaireStudyUnit4list\Block\VendorSorter
 * @var \Magento\Framework\Escaper $escaper
 */
$vendorSortingKeys = $block->getSortingKeys();
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $escaper->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php
        foreach ($vendorSortingKeys as $sortingKey) {
            ?>
            <option value="<?= $escaper->escapeHtml(__($sortingKey)) ?>"
                <?php
                if ($sortingKey === $block->getCurrentOrder()) {
                    ?>
                    selected="selected"
                    <?php
                }
                ?>
            >
                <?= $escaper->escapeHtml(__($sortingKey)) ?>
            </option>
            <?php
        }
        ?>
    </select>

    <?php
    if ($block->getCurrentOrderDirection() == 'asc') {
        ?>
        <a title="<?= $escaper->escapeHtml(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $escaper->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
        <?php
    } else {
        ?>
        <a title="<?= $escaper->escapeHtml(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $escaper->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
        <?php
    }
    ?>

</div>
<script>
    require(['jquery'],

        function ($) {
            'use strict';

            $(document).ready(function () {

                function changeUrl(paramName, paramValue) {
                    let url = window.location.href;

                    if (url.includes(paramName + '=')) {
                        let urlParamRegEx = new RegExp(paramName + '=([^&]*)', 'g');
                        url = url.replace(urlParamRegEx, paramName + '=' + paramValue);
                    } else {
                        let urlPrefix = '';
                        if (url.includes('?')) {
                            urlPrefix = '&';
                        } else {
                            urlPrefix = '?';
                        }
                        url += urlPrefix + paramName + '=' + paramValue;
                    }
                    window.location.href = url;
                }

                $('.sorter-action').on('click', function (event) {
                    event.preventDefault();
                    let sortingDirection = $(event.target).attr('data-value');
                    let sortingDirectionUrlParam = '<?php echo \Lumav\DaireStudyUnit4list\Model\Vendor::VENDOR_LIST_SORTING_DIRECTION_PARAM ?>';
                    changeUrl(sortingDirectionUrlParam, sortingDirection);
                });

                $('#sorter').on('change', function () {
                    let sortingKey = this.value;
                    let sortingUrlParam = '<?php echo \Lumav\DaireStudyUnit4list\Model\Vendor::VENDOR_LIST_SORTING_PARAM ?>';
                    changeUrl(sortingUrlParam, sortingKey);

                });
            })
        });

</script>
